# Generated by Django 4.0.3 on 2022-03-28 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('short_urls', '0002_shorturl_slug'),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturlvisit',
            name='short_url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='short_urls.shorturl'),
        ),
    ]
